# Native Windows build; CUDA device functions stay in one translation unit.
[CmdletBinding()]
param(
    [switch]$Rebuild,
    [ValidatePattern('^(86|120)(,(86|120))*$')]
    [string]$CudaArch = '86,120',
    [ValidateSet(128,256,512)]
    [int]$Threads = 512,
    [ValidateSet(16,32)]
    [int]$Tile = 32,
    [switch]$Pipeline,
    [string]$OutputDirectory = '',
    [switch]$Run,
    [string[]]$TrainingArgs = @()
)
$ErrorActionPreference = 'Stop'
$totalTimer = [Diagnostics.Stopwatch]::StartNew()
if ($TrainingArgs.Count -and -not $Run) { throw 'TrainingArgs requires -Run.' }
$outDir = if ($OutputDirectory) { [IO.Path]::GetFullPath($OutputDirectory) } else {
    Join-Path $PSScriptRoot 'build'
}
[void][IO.Directory]::CreateDirectory($outDir)
$cuda134 = Join-Path $env:ProgramFiles 'NVIDIA GPU Computing Toolkit\CUDA\v13.4'
$cuda = if ($env:TURBOGPT_CUDA) { $env:TURBOGPT_CUDA } elseif (Test-Path -LiteralPath $cuda134) {
    $cuda134
} elseif ($env:CUDA_PATH) {
    $env:CUDA_PATH
} else { 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4' }
$nvcc = Join-Path $cuda 'bin\nvcc.exe'
if (-not (Test-Path -LiteralPath $nvcc)) { throw 'CUDA not found; set TURBOGPT_CUDA.' }
# HEAD, then the working-tree diff after a blank line. A scratch index includes
# untracked files without touching the real index.
function Get-Revision {
    $ErrorActionPreference = 'Continue'
    $hash = git -C $PSScriptRoot rev-parse HEAD 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $hash) { return [Text.Encoding]::UTF8.GetBytes('unknown') }
    # Git failed to write this index inside build/ on one machine; the temp directory is safe.
    $scratch = Join-Path ([IO.Path]::GetTempPath()) "turbogpt-revision-$PID"
    $index = "$scratch.index"
    $diff = "$scratch.diff"
    $realIndex = git -C $PSScriptRoot rev-parse --path-format=absolute --git-path index 2>$null
    $previousIndex = $env:GIT_INDEX_FILE
    try {
        if ($realIndex -and (Test-Path -LiteralPath $realIndex)) {
            Copy-Item -LiteralPath $realIndex -Destination $index -Force
        }
        $env:GIT_INDEX_FILE = $index
        git -C $PSScriptRoot add -A 2>$null
        if ($LASTEXITCODE -ne 0) { throw 'git add failed for the revision diff.' }
        git -C $PSScriptRoot diff --cached --no-color --no-ext-diff "--output=$diff" HEAD 2>$null
        if ($LASTEXITCODE -ne 0) { throw 'git diff failed for the revision diff.' }
    } finally {
        $env:GIT_INDEX_FILE = $previousIndex
        Remove-Item -LiteralPath $index -ErrorAction SilentlyContinue
    }
    $bytes = [Collections.Generic.List[byte]]::new([Text.Encoding]::UTF8.GetBytes($hash.Trim()))
    $patch = [IO.File]::ReadAllBytes($diff)
    Remove-Item -LiteralPath $diff
    if ($patch.Length) {
        $bytes.AddRange([Text.Encoding]::UTF8.GetBytes("`n`n"))
        $bytes.AddRange($patch)
    }
    return $bytes.ToArray()
}

# The revision is its own unit: a commit or edit recompiles only it and relinks.
function Write-RevisionSource([string]$Path) {
    $bytes = Get-Revision
    $text = [Text.StringBuilder]::new()
    [void]$text.Append("// Generated by build.ps1; see revision.h.`n#include <cstddef>`n`n")
    [void]$text.Append("extern const unsigned char turbogpt_revision[] = {`n")
    for ($i = 0; $i -lt $bytes.Length; $i += 32) {
        $last = [Math]::Min($i + 31, $bytes.Length - 1)
        [void]$text.Append('    ').Append(($bytes[$i..$last] -join ',')).Append(",`n")
    }
    [void]$text.Append("};`nextern const size_t turbogpt_revision_size = $($bytes.Length);`n")
    $content = $text.ToString()
    if (-not (Test-Path -LiteralPath $Path) -or [IO.File]::ReadAllText($Path) -ne $content) {
        [IO.File]::WriteAllText($Path, $content, [Text.UTF8Encoding]::new($false))
    }
}
$revisionSource = Join-Path $outDir 'revision.cpp'
Write-RevisionSource $revisionSource

$flags = @('-O3', '-std=c++17', '--use_fast_math', '-lineinfo', '--threads', '0',
    '--split-compile', '0', '-Xcompiler', '/Zc:preprocessor,/MT')
$flags += @("-DTURBOGPT_THREADS=$Threads", "-DTURBOGPT_TILE=$Tile", "-DTURBOGPT_PIPELINE=$([int]$Pipeline.IsPresent)")
foreach ($target in $CudaArch.Split(',')) {
    $flags += @('-gencode', "arch=compute_$target,code=sm_$target")
}
$signature = $nvcc + "`n" + ($flags -join "`n")

# Follow local includes so a small edit recompiles only affected modules.
function Get-SourceDigest([string]$Source) {
    $pending = [Collections.Generic.Stack[string]]::new()
    $seen = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    $pending.Push([IO.Path]::Combine($PSScriptRoot, $Source))
    while ($pending.Count) {
        $path = [IO.Path]::GetFullPath($pending.Pop())
        if (-not $seen.Add($path)) { continue }
        $text = [IO.File]::ReadAllText($path)
        foreach ($include in [regex]::Matches($text, '(?m)^\s*#include\s+"([^"]+)"')) {
            $pending.Push((Join-Path (Split-Path $path) $include.Groups[1].Value))
        }
    }
    $bytes = [IO.MemoryStream]::new()
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        # GPU architecture/tile choices do not invalidate the ordinary C++ units.
        $unitSignature = if ([IO.Path]::GetExtension($Source) -eq '.cu') { $signature } else {
            'MSVC /O2 /std:c++17 /EHsc /MT'
        }
        $prefix = [Text.Encoding]::UTF8.GetBytes($unitSignature)
        $bytes.Write($prefix, 0, $prefix.Length)
        foreach ($path in ($seen | Sort-Object)) {
            $sourceBytes = [IO.File]::ReadAllBytes($path)
            $bytes.Write($sourceBytes, 0, $sourceBytes.Length)
        }
        $bytes.Position = 0
        return [BitConverter]::ToString($sha.ComputeHash($bytes)).Replace('-', '').ToLowerInvariant()
    } finally { $sha.Dispose(); $bytes.Dispose() }
}

$sources = [ordered]@{cuda='cuda/runtime.cu'; engine_state='cuda/engine_state.cu';
    checkpoint='checkpoint.cpp'; sampling='sampling.cpp'; train='train.cpp';
    trainer='trainer.cpp'; tensorboard='tensorboard.cpp'; training_log='training_log.cpp';
    dataset='dataset.cpp'; loss_summary='loss_summary.cpp'; model='model.cpp'; report='report.cpp'
    revision=$revisionSource}
$manifest = Join-Path $outDir 'build.json'
$old = if (Test-Path -LiteralPath $manifest) { Get-Content -LiteralPath $manifest -Raw | ConvertFrom-Json } else { @{} }
$hashes = @{}
$objects = @()
$cudaObjects = @()
$phases = [ordered]@{}
$compilerReady = $false
$previousEnvironment = @{}

function Invoke-Compiler([string]$Phase, [string]$Program, [string[]]$Arguments) {
    if (-not $script:compilerReady) {
        $vc = 'C:\Program Files\Visual Studio\2022\VC\Auxiliary\Build\vcvars64.bat'
        if (-not (Test-Path -LiteralPath $vc)) {
            $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
            if (Test-Path -LiteralPath $vswhere) {
                $install = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
                if ($install) { $vc = Join-Path $install 'VC\Auxiliary\Build\vcvars64.bat' }
            }
        }
        if (Test-Path -LiteralPath $vc) {
            $compilerVars = & $env:ComSpec /d /s /c ('call "' + $vc + '" >nul && set')
            if ($LASTEXITCODE -ne 0) { throw 'MSVC environment setup failed.' }
            foreach ($line in $compilerVars) {
                if ($line -match '^([^=]+)=(.*)$') {
                    $key, $value = $Matches[1], $Matches[2]
                    $previousEnvironment[$key] = [Environment]::GetEnvironmentVariable($key, 'Process')
                    [Environment]::SetEnvironmentVariable($key, $value, 'Process')
                }
            }
        } elseif (-not (Get-Command cl.exe -ErrorAction SilentlyContinue)) {
            throw 'MSVC not found; use a Visual Studio developer shell.'
        }
        if (-not $previousEnvironment.ContainsKey('PATH')) { $previousEnvironment['PATH'] = $env:PATH }
        $env:PATH = (Join-Path $cuda 'bin') + ';' + $env:PATH
        if (Test-Path -LiteralPath $manifest) { Remove-Item -LiteralPath $manifest }
        $script:compilerReady = $true
    }
    $phaseTimer = [Diagnostics.Stopwatch]::StartNew()
    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) { throw "$Phase failed with exit code $LASTEXITCODE." }
    $phases[$Phase] = $phaseTimer.Elapsed.TotalSeconds
}

$exe = Join-Path $outDir 'turbogpt.exe'
$dll = Join-Path $outDir 'turbogpt.dll'
$changed = $false
$cudaChanged = $false
Push-Location -LiteralPath $outDir
try {
    foreach ($unit in $sources.Keys) {
        $hashes[$unit] = Get-SourceDigest $sources[$unit]
        $source = [IO.Path]::Combine($PSScriptRoot, $sources[$unit])
        $object = Join-Path $outDir "$unit.obj"
        $objects += $object
        if ([IO.Path]::GetExtension($source) -eq '.cu') { $cudaObjects += $object }
        if ($Rebuild -or $old.$unit -ne $hashes[$unit] -or -not (Test-Path -LiteralPath $object)) {
            if ([IO.Path]::GetExtension($source) -eq '.cu') {
                Invoke-Compiler "$($unit)_compile_seconds" $nvcc ($flags + @('-c', $source, '-o', $object))
                $cudaChanged = $true
            } else {
                Invoke-Compiler "$($unit)_compile_seconds" 'cl.exe' @(
                    '/nologo', '/O2', '/std:c++17', '/EHsc', '/MT', '/c', $source, "/Fo$object")
            }
            $changed = $true
        }
    }
    if ($changed -or -not (Test-Path -LiteralPath $exe)) {
        # Only the DLL needs turbogpt.lib; the exe writing it too races a virus scan of the
        # fresh file and the DLL link then fails with LNK1114.
        Invoke-Compiler 'exe_link_seconds' $nvcc (@('-Xcompiler', '/MT', '-Xlinker', '/NOIMPLIB,/NOEXP') +
            $objects + @('-o', $exe))
    }
    # The DLL exposes the same GPU code to the oracle.
    if ($cudaChanged -or -not (Test-Path -LiteralPath $dll)) {
        Invoke-Compiler 'dll_link_seconds' $nvcc (@('-Xcompiler', '/MT', '-shared') + $cudaObjects + @('-o', $dll))
    }
    [IO.File]::WriteAllText($manifest, ($hashes | ConvertTo-Json), [Text.UTF8Encoding]::new($false))
    $phases['build_seconds'] = $totalTimer.Elapsed.TotalSeconds
    $phases['recompiled'] = $changed
    @{build=$phases} | ConvertTo-Json -Compress
} finally {
    Pop-Location
    foreach ($key in $previousEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable($key, $previousEnvironment[$key], 'Process')
    }
}
if ($Run) {
    & $exe @TrainingArgs
    $trainingExitCode = $LASTEXITCODE
    $phases['build_plus_process_seconds'] = $totalTimer.Elapsed.TotalSeconds
    @{total=$phases} | ConvertTo-Json -Compress
    if ($trainingExitCode -ne 0) { throw "Training failed with exit code $trainingExitCode." }
}
